[build]
  command = "pip install -r requirements.txt"
  functions = "functions"
  publish = "public"

[functions]
  directory = "functions"
  external_node_modules = []
  included_files = ["*.py"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/:splat"
  status = 200
